<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1ZZQ3oX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1ZZQ3oX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1ZZQ3oX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1ZZQ3oX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1ZZQ3oX\App_KernelDevDebugContainer([
    'container.build_hash' => '1ZZQ3oX',
    'container.build_id' => 'd1382050',
    'container.build_time' => 1614670980,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1ZZQ3oX');
