<?php

namespace ContainerZCuS4eu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_1rv1kVkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.1rv1kVk' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/MessageHandler/AddDetailHandler.php';

        return $container->privates['.messenger.handler_descriptor.1rv1kVk'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\MessageHandler\AddDetailHandler(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService())), []);
    }
}
