<?php

namespace ContainerQcxUom9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sf35pY1Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.Sf35pY1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sf35pY1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'detailRepository' => ['privates', 'App\\Repository\\DetailRepository', 'getDetailRepositoryService', true],
        ], [
            'detailRepository' => 'App\\Repository\\DetailRepository',
        ]);
    }
}
