<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQcxUom9\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQcxUom9/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQcxUom9.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQcxUom9\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerQcxUom9\App_KernelTestDebugContainer([
    'container.build_hash' => 'QcxUom9',
    'container.build_id' => '4ffe5046',
    'container.build_time' => 1605670906,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQcxUom9');
