<?php

namespace ContainerOPF5fHJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_70pgxZ6Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.70pgxZ6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.70pgxZ6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ApiController::createUser' => ['privates', '.service_locator.7ehozm5', 'get_ServiceLocator_7ehozm5Service', true],
            'App\\Controller\\ApiController::getAllUsers' => ['privates', '.service_locator.FXD6KYr', 'get_ServiceLocator_FXD6KYrService', true],
            'App\\Controller\\ApiController::getAllUsersDetails' => ['privates', '.service_locator.Sf35pY1', 'get_ServiceLocator_Sf35pY1Service', true],
            'App\\Controller\\ApiController::getOneUser' => ['privates', '.service_locator.FXD6KYr', 'get_ServiceLocator_FXD6KYrService', true],
            'App\\Controller\\ApiController::getOneUserDetail' => ['privates', '.service_locator.Sf35pY1', 'get_ServiceLocator_Sf35pY1Service', true],
            'App\\Controller\\ApiController::index' => ['privates', '.service_locator._nRHRBM', 'get_ServiceLocator_NRHRBMService', true],
            'App\\Controller\\ApiController::updateUserPassword' => ['privates', '.service_locator.7ehozm5', 'get_ServiceLocator_7ehozm5Service', true],
            'App\\Controller\\DepositController::index' => ['privates', '.service_locator.mXIf.tv', 'get_ServiceLocator_MXIf_TvService', true],
            'App\\Controller\\DetailController::index' => ['privates', '.service_locator.79gRDgT', 'get_ServiceLocator_79gRDgTService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.mXIf.tv', 'get_ServiceLocator_MXIf_TvService', true],
            'App\\Controller\\RegisterController::register' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\WithdrawalController::index' => ['privates', '.service_locator.mXIf.tv', 'get_ServiceLocator_MXIf_TvService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\ApiController:createUser' => ['privates', '.service_locator.7ehozm5', 'get_ServiceLocator_7ehozm5Service', true],
            'App\\Controller\\ApiController:getAllUsers' => ['privates', '.service_locator.FXD6KYr', 'get_ServiceLocator_FXD6KYrService', true],
            'App\\Controller\\ApiController:getAllUsersDetails' => ['privates', '.service_locator.Sf35pY1', 'get_ServiceLocator_Sf35pY1Service', true],
            'App\\Controller\\ApiController:getOneUser' => ['privates', '.service_locator.FXD6KYr', 'get_ServiceLocator_FXD6KYrService', true],
            'App\\Controller\\ApiController:getOneUserDetail' => ['privates', '.service_locator.Sf35pY1', 'get_ServiceLocator_Sf35pY1Service', true],
            'App\\Controller\\ApiController:index' => ['privates', '.service_locator._nRHRBM', 'get_ServiceLocator_NRHRBMService', true],
            'App\\Controller\\ApiController:updateUserPassword' => ['privates', '.service_locator.7ehozm5', 'get_ServiceLocator_7ehozm5Service', true],
            'App\\Controller\\DepositController:index' => ['privates', '.service_locator.mXIf.tv', 'get_ServiceLocator_MXIf_TvService', true],
            'App\\Controller\\DetailController:index' => ['privates', '.service_locator.79gRDgT', 'get_ServiceLocator_79gRDgTService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.mXIf.tv', 'get_ServiceLocator_MXIf_TvService', true],
            'App\\Controller\\RegisterController:register' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\WithdrawalController:index' => ['privates', '.service_locator.mXIf.tv', 'get_ServiceLocator_MXIf_TvService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\ApiController::createUser' => '?',
            'App\\Controller\\ApiController::getAllUsers' => '?',
            'App\\Controller\\ApiController::getAllUsersDetails' => '?',
            'App\\Controller\\ApiController::getOneUser' => '?',
            'App\\Controller\\ApiController::getOneUserDetail' => '?',
            'App\\Controller\\ApiController::index' => '?',
            'App\\Controller\\ApiController::updateUserPassword' => '?',
            'App\\Controller\\DepositController::index' => '?',
            'App\\Controller\\DetailController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\RegisterController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\WithdrawalController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ApiController:createUser' => '?',
            'App\\Controller\\ApiController:getAllUsers' => '?',
            'App\\Controller\\ApiController:getAllUsersDetails' => '?',
            'App\\Controller\\ApiController:getOneUser' => '?',
            'App\\Controller\\ApiController:getOneUserDetail' => '?',
            'App\\Controller\\ApiController:index' => '?',
            'App\\Controller\\ApiController:updateUserPassword' => '?',
            'App\\Controller\\DepositController:index' => '?',
            'App\\Controller\\DetailController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\RegisterController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\WithdrawalController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
