<?php

namespace Container1ZZQ3oX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_79gRDgTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.79gRDgT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.79gRDgT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'detailRepository' => ['privates', 'App\\Repository\\DetailRepository', 'getDetailRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'detailRepository' => 'App\\Repository\\DetailRepository',
            'security' => '?',
        ]);
    }
}
