<?php

namespace Container1ZZQ3oX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepositTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\DepositType' shared autowired service.
     *
     * @return \App\Form\DepositType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/DepositType.php';

        return $container->privates['App\\Form\\DepositType'] = new \App\Form\DepositType();
    }
}
